### ISSUE TITLE
I think the root pom is missing

### ISSUE THREAD

**Issue by cschneider** [toedter/e4-tutorial#3]

**Comment by toedter** [comment]
The root pom is in project org.eclipse.e4.tutorial.contacts.build.tycho. Just open a shell in the directory org.eclipse.e4.tutorial.contacts.build.tycho and invoke "mvn clean install".

**Comment by cschneider** [comment]
Thx for the hint ... To my shame it is even described in the readme ...
Is there a special reason why the root pom is not in the root dir? I think it would be a lot more obvious for maven people what to do.

**Comment by toedter** [comment]
the reason was that you can import the build project as an Eclipse project. This is best practice in the Eclipse world.
